### ISSUE TITLE
Tensor#matmul Error: undefined method 'buffer' for Tensor(Float32)

### ISSUE THREAD

**Issue by jtanderson** [crystal-data/num.cr#31]
This code, taken partially from the readme:

```crystal
a = [[1, 2], [3, 4]].to_tensor.astype(Float32)
b = [[3, 4], [5, 6]].to_tensor.astype(Float32)

puts a.matmul(b)
```

Throws `Error: undefined method 'buffer' for Tensor(Float32)` after expanding the `blas` macro. 

Edit: From some quick testing, it looks like a swap of `.storage` instead of `.buffer` in `tensor/linalg#matmul` will fix this. Putting together a PR but let me know if this isn't the right way to fix

**Comment by christopherzimmerman** [comment]
@jtanderson I think `to_unsafe` should be used intstead of `buffer` in all cases now.

**Comment by christopherzimmerman** [comment]
This is fixed on master.  You will probably need to clear your `shard.lock`.  I am working on a stable `0.4.0` release right now, and after that I'll start versioning/tagging appropriately.

**Comment by jtanderson** [comment]
Great!
